#!/bin/bash

DEVICE_NAME="${BLOCK_INSTANCE:-Logitech}"

DEVICE_INFO=$(lsusb | grep -i "${DEVICE_NAME}")

if [[ "${DEVICE_INFO}" != "" ]]; then
  
  echo "on"

  echo "on"
  echo "#FF0000"
  #exit 33;
else
  echo ""
fi
